version: '3.8'
services:
  db:
      image: postgres:latest
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 12345Qa!
        POSTGRES_DB: komronbek
      ports:
        - "5433:5432"
      volumes:
        - ./db-scripts:/docker-entrypoint-initdb.d
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  
